### ISSUE TITLE
add-dialog.png

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.it-it#13]
NEED  WRAPPING TEXT - see attached screenshot

![add-dialog](https://user-images.githubusercontent.com/64255878/147210210-74b5d2c0-b822-437c-b9cb-b1e8da03d7a0.png)

**Comment by stonezy123** [comment]
https://dev.azure.com/ceapex/CEINTL/_workitems/edit/691513

**Comment by stonezy123** [comment]
fixed.
add-trigger.png
![image](https://user-images.githubusercontent.com/49666210/190941955-03e997fb-0881-4332-a809-bfe290cf10c9.png)
