### ISSUE TITLE
add-trigger.png

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.it-it#14]
NEED  WRAPPING TEXT - see attached screenshot

![add-trigger](https://user-images.githubusercontent.com/64255878/147210393-ea69c168-db6d-4330-b6ed-c4cfcbc77a54.png)

**Comment by stonezy123** [comment]
https://dev.azure.com/ceapex/CEINTL/_workitems/edit/691513

**Comment by stonezy123** [comment]
fixed.
![image](https://user-images.githubusercontent.com/49666210/190942026-53977769-3dfa-484c-99b7-ecfc4dc4ff3e.png)
