### ISSUE TITLE
getWeather-dialog-2.png

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.it-it#15]
NEED  WRAPPING TEXT - see attached screenshot

![getWeather-dialog-2](https://user-images.githubusercontent.com/64255878/147210582-dcbebeba-0e48-4541-9d75-a589202cd895.png)

**Comment by stonezy123** [comment]
https://dev.azure.com/ceapex/CEINTL/_workitems/edit/691513

**Comment by stonezy123** [comment]
fixed.
![image](https://user-images.githubusercontent.com/49666210/190941885-0fc45bee-1191-4163-bc20-51765798ffc6.png)
