### ISSUE TITLE
resource_group_variables.png

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.it-it#16]
TEXT/ICONS OVERLAPPING - see attached screenshot

![resource_group_variables](https://user-images.githubusercontent.com/64255878/147210944-469d5ced-7f2e-48e7-aba3-a75591da5481.png)

**Comment by stonezy123** [comment]
https://dev.azure.com/ceapex/CEINTL/_workitems/edit/691513

**Comment by stonezy123** [comment]
![image](https://user-images.githubusercontent.com/49666210/190941760-2af822aa-e6c6-452a-b6ef-a55f89076071.png)
