### ISSUE TITLE
video-indexer-edit-name.png

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.it-it#17]
TEXT/ICONS OVERLAPPING - see attached screenshot

![video-indexer-edit-name](https://user-images.githubusercontent.com/64255878/147211036-07c4de12-5a79-4630-ab06-b8c3ee08b1f3.png)

**Comment by stonezy123** [comment]
https://dev.azure.com/ceapex/CEINTL/_workitems/edit/691513

**Comment by stonezy123** [comment]
fixed.
![image](https://user-images.githubusercontent.com/49666210/190941706-99e1be81-1c39-4e4a-94b6-aedb30281d3c.png)
