### ISSUE TITLE
video-indexer-insights.png

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.it-it#18]
SEVERAL LAYOUT ISSUES - see attached screenshot

![video-indexer-insights](https://user-images.githubusercontent.com/64255878/147211300-6619d1c4-69de-4935-b394-69a98b71bba8.png)

**Comment by stonezy123** [comment]
https://dev.azure.com/ceapex/CEINTL/_workitems/edit/691513

**Comment by stonezy123** [comment]
fixed.
![image](https://user-images.githubusercontent.com/49666210/190941631-80742c09-618c-4967-9e25-76ec7fc1330b.png)
