### ISSUE TITLE
video-indexer-known-person.png

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.it-it#19]
SEVERAL LAYOUT ISSUES - see attached screenshot

![video-indexer-known-person](https://user-images.githubusercontent.com/64255878/147211377-d026ef7a-a72f-456e-8de9-df35c530a3d6.png)

**Comment by stonezy123** [comment]
https://dev.azure.com/ceapex/CEINTL/_workitems/edit/691513

**Comment by stonezy123** [comment]
fixed.
![image](https://user-images.githubusercontent.com/49666210/190941459-62655d1e-bf66-41a3-b6f1-fba143a927ce.png)
