### ISSUE TITLE
video-indexer-search.png

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.it-it#20]
SEVERAL LAYOUT ISSUES - see attached screenshot

![video-indexer-search](https://user-images.githubusercontent.com/64255878/147211461-84c7e67d-0f76-4258-8cca-072515fc7018.png)

**Comment by stonezy123** [comment]
https://dev.azure.com/ceapex/CEINTL/_workitems/edit/691513

**Comment by stonezy123** [comment]
fixed.
![image](https://user-images.githubusercontent.com/49666210/190941392-76d59a77-b9ef-4a70-9698-5483feecf475.png)
