### ISSUE TITLE
video-indexer-transcript.png

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.it-it#22]
NEED  WRAPPING TEXT - see attached screenshot

![video-indexer-transcript](https://user-images.githubusercontent.com/64255878/147211727-05923a4e-f666-452c-9d42-21948cc20fe6.png)

**Comment by stonezy123** [comment]
https://dev.azure.com/ceapex/CEINTL/_workitems/edit/691513

**Comment by stonezy123** [comment]
fixed.
![image](https://user-images.githubusercontent.com/49666210/190941226-86c4caa7-db69-43f7-9053-67a83be1503b.png)
