### ISSUE TITLE
video-indexer-unknown-person.png

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AI-102-AIEngineer.it-it#23]
TEXT/ICONS OVERLAPPING - see attached screenshot

![video-indexer-unknown-person](https://user-images.githubusercontent.com/64255878/147211798-67cb11ac-a6cc-45e9-adb9-c4f10d890188.png)

**Comment by stonezy123** [comment]
https://dev.azure.com/ceapex/CEINTL/_workitems/edit/691513

**Comment by stonezy123** [comment]
image fixed.
![image](https://user-images.githubusercontent.com/49666210/190940920-1b07ee89-a9af-4494-82d7-449699bf4e02.png)
